linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck  # Disable errcheck to avoid defer errors

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - tmp
  exclude-files:
    - ".*_test\\.go$"
  
run:
  timeout: 5m

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
